name: Calculate participants weeks

on:
  workflow_dispatch:

jobs:
  check_repo_commits:
    runs-on: self-hosted
    env:
      START_DATE_1: 06:09:2021
      REPO_1: Rise
      AUTHOR_1: VladimirBrejcha
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Calculate
        run: |
          printf "%s\n" "Stats for $AUTHOR_1"
          swift ${GITHUB_WORKSPACE}/ChallengeActiveWeeksCalculator.swift -since $START_DATE_1 -repo $REPO_1 -author $AUTHOR_1
