name: Calculate participants weeks

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  check_repo_commits:
    runs-on: self-hosted
    env:
      START_DATE_1: 06:09:2021
      REPO_1: RedmineClient
      AUTHOR_1: Ernest0-Production
      
      START_DATE_2: 06:09:2021
      REPO_2: Rise
      AUTHOR_2: VladimirBrejcha
      
      START_DATE_3: 13:09:2021
      REPO_3: 100DaysOfSwift
      AUTHOR_3: LeshaAleshaaa
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Calculate
        run: |
          printf "%s\n" "Stats for $AUTHOR_1"
          swift ${GITHUB_WORKSPACE}/ChallengeActiveWeeksCalculator.swift -since $START_DATE_1 -repo $REPO_1 -author $AUTHOR_1
          printf "%s\n" "Stats for $AUTHOR_2"
          swift ${GITHUB_WORKSPACE}/ChallengeActiveWeeksCalculator.swift -since $START_DATE_2 -repo $REPO_2 -author $AUTHOR_2
          printf "%s\n" "Stats for $AUTHOR_3"
          swift ${GITHUB_WORKSPACE}/ChallengeActiveWeeksCalculator.swift -since $START_DATE_3 -repo $REPO_3 -author $AUTHOR_3
